name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: abubakar-shahid
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: EndBug/add-and-commit@v7
        with:
          branch: output
          message: "Generate contribution snake"
          add: "dist/*"
